name: "Mehring's Page"
favicon: null
layout_spectrum: 0.73483
typography_spectrum: 0.26743
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#fece00'
    - '#cb161b'
    - '#020204'
    - '#8f9095'
  brandStrength: 0.5
  lightness: 0.8125
  saturation: 0
  rhythmicContrast: 0.5
purpose: []
