name: "Mehring's Page"
favicon: null
layout_spectrum: 0.5435801455751061
typography_spectrum: 0.06567064160481095
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.9306142616551369
  lightness: 0.9274282872211188
  saturation: 0.8944065414834768
  rhythmicContrast: 0.5187025247141719
purpose: []
