name: "Mehring's Page"
favicon: null
layout_spectrum: 1
typography_spectrum: 0.26743
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#49484d'
    - '#000000'
    - '#ce3e3d'
    - '#fb9401'
  brandStrength: 1
  lightness: 0.5
  saturation: 0
  rhythmicContrast: 0.5
purpose: []
