name: "Mehring's Page"
favicon: null
layout_spectrum: 1
typography_spectrum: 0.26743
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#dad6ca'
    - '#0f0d12'
    - '#a47037'
    - '#f4ffff'
    - '#70513d'
  brandStrength: 0.9306142616551369
  lightness: 0.9274282872211188
  saturation: 0.8944065414834768
  rhythmicContrast: 0.5187025247141719
purpose: []
